from tkinter import *

root=Tk()
root.geometry("300x200")
root.title("Spider")
menu=Menu(root)
root.config(menu=menu)
filemenu=Menu(menu)
Edit=Menu(menu)
menu.add_cascade(label='File', menu=filemenu)
filemenu.add_command(label='New')
filemenu.add_command(label='Open...')
filemenu.add_separator()
menu.add_cascade(label='Edit', menu=Edit)
filemenu.add_command(label='config')
filemenu.add_command(label='Exit', command=root.quit)
helpmenu = Menu(menu)
menu.add_cascade(label='Help', menu=helpmenu)
helpmenu.add_command(label='About')
mainloop()
